### ISSUE TITLE
Alaotsikoiden boldaus

### ISSUE THREAD

**Issue by joonaris** [GispoCoding/GE002_Suunnittelu_editointi_ja_datan_hallinta_QGISilla#1]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/104818918/225852737-69bb4a12-d007-43ba-bf12-c413df208f6e.png">
Alaotsikoiden boldauksen/lihavoinnin voisi laittaa pois

**Comment by JuhoErvasti** [comment]
Korjattu.
